# Generated by Django 2.0.7 on 2018-12-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('type', models.IntegerField(choices=[('private', 1), ('group', 2), ('supergroup', 3), ('channel', 4)])),
            ],
        ),
        migrations.CreateModel(
            name='TelegramReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='TelegramSent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('deleted', models.BooleanField()),
                ('forwarded', models.BooleanField()),
            ],
        ),
    ]
