# Generated by Django 2.1.2 on 2018-12-22 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.IntegerField()),
                ('type', models.IntegerField(choices=[('private', 1), ('group', 2), ('supergroup', 3), ('channel', 4)])),
                ('title', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('all_members_are_administrators', models.BooleanField()),
                ('description', models.CharField(max_length=255)),
                ('invite_link', models.CharField(max_length=45)),
                ('pinned', models.BooleanField()),
                ('sticker_set_name', models.CharField(max_length=64)),
                ('can_set_sticker_set', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_file_id', models.CharField(max_length=45)),
                ('big_file_id', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('forward_from_message_id', models.IntegerField()),
                ('forward_date', models.DateTimeField()),
                ('edit_date', models.DateTimeField()),
                ('text', models.CharField(max_length=4096)),
                ('caption', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('deleted', models.BooleanField()),
                ('forwarded', models.BooleanField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='django_telegram.Chat')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=45)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('file_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('is_bot', models.BooleanField()),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=30)),
                ('language_code', models.CharField(max_length=35)),
            ],
        ),
        migrations.DeleteModel(
            name='TelegramChat',
        ),
        migrations.DeleteModel(
            name='TelegramReceived',
        ),
        migrations.DeleteModel(
            name='TelegramSent',
        ),
        migrations.AddField(
            model_name='message',
            name='forward_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_of_forwarded_messages', to='django_telegram.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='forward_from_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_of_forwarded_messages', to='django_telegram.Chat'),
        ),
        migrations.AddField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='django_telegram.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='django_telegram.Location'),
        ),
        migrations.AddField(
            model_name='message',
            name='photo',
            field=models.ManyToManyField(to='django_telegram.PhotoSize'),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='django_telegram.Message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='django_telegram.ChatPhoto'),
        ),
    ]
