# Generated by Django 2.1.2 on 2018-12-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0004_bot_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='name',
            field=models.CharField(default='The Butler Bot', max_length=50),
            preserve_default=False,
        ),
    ]
