# Generated by Django 2.1.2 on 2018-12-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0005_bot_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='enabled',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
