# Generated by Django 2.1.2 on 2018-12-29 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0006_bot_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='all_members_are_administrators',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='can_set_sticker_set',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='first_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='invite_link',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='django_telegram.ChatPhoto'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='pinned',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sticker_set_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='caption',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='edit_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='forward_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='forward_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_of_forwarded_messages', to='django_telegram.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='forward_from_chat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_of_forwarded_messages', to='django_telegram.Chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='forward_from_message_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='django_telegram.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_telegram.Location'),
        ),
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.ManyToManyField(null=True, to='django_telegram.PhotoSize'),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_to_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='django_telegram.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='language_code',
            field=models.CharField(max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
