# Generated by Django 2.1.2 on 2018-12-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0008_auto_20181229_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatphoto',
            name='big_file_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='chatphoto',
            name='small_file_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='photosize',
            name='file_id',
            field=models.CharField(max_length=100),
        ),
    ]
