# Generated by Django 2.1.2 on 2018-12-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0009_auto_20181229_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_by_bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages_sent', to='django_telegram.Bot'),
        ),
    ]
