# Generated by Django 2.1.2 on 2018-12-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0010_message_sent_by_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_to_bot',
            field=models.ManyToManyField(null=True, related_name='messages_received', to='django_telegram.Bot'),
        ),
    ]
