# Generated by Django 2.1.2 on 2018-12-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0011_message_sent_to_bot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='photo',
            field=models.ManyToManyField(to='django_telegram.PhotoSize'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_to_bot',
            field=models.ManyToManyField(related_name='messages_received', to='django_telegram.Bot'),
        ),
    ]
