# Generated by Django 2.1.2 on 2018-12-31 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0013_auto_20181230_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_instances', to='django_telegram.Bot')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_instances', to='django_telegram.Chat')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='function_path',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stateinstance',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='django_telegram.State'),
        ),
        migrations.AddField(
            model_name='stateinstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_instances', to='django_telegram.User'),
        ),
    ]
