# Generated by Django 2.1.2 on 2018-12-31 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0014_auto_20181231_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='default_group_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bots_with_group_default', to='django_telegram.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='default_private_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bots_with_private_default', to='django_telegram.State'),
            preserve_default=False,
        ),
    ]
