# Generated by Django 2.1.2 on 2018-12-31 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0015_auto_20181231_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='initial_group_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bots_with_group_initial', to='django_telegram.State'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bot',
            name='initial_private_state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='bots_with_private_initial', to='django_telegram.State'),
            preserve_default=False,
        ),
    ]
