# Generated by Django 2.1.2 on 2019-01-03 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0016_auto_20181231_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('class_path', models.CharField(max_length=200)),
                ('kwargs_json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HandlerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handler_instances', to='django_telegram.Bot')),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='django_telegram.Handler')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='stateinstance',
            unique_together={('chat', 'user', 'bot')},
        ),
    ]
