# Generated by Django 2.1.2 on 2019-01-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0017_auto_20190103_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='handler',
            name='function_path',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
