# Generated by Django 2.1.2 on 2019-01-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0018_handler_function_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='handlerinstance',
            name='group',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
