# Generated by Django 2.1.2 on 2019-01-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0019_handlerinstance_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateinstance',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_instances', to='django_telegram.Message'),
        ),
        migrations.AlterUniqueTogether(
            name='stateinstance',
            unique_together={('chat', 'user', 'bot', 'message')},
        ),
    ]
