# Generated by Django 2.1.2 on 2019-01-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0020_auto_20190104_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateinstance',
            name='kwargs_json',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
