# Generated by Django 2.1.2 on 2019-01-06 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0021_stateinstance_kwargs_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_telegram.Chat')),
                ('effective_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='django_telegram.Message')),
                ('effective_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_telegram.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='bot',
            name='log_all_messages_received',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='log_all_messages_sent',
        ),
        migrations.AlterField(
            model_name='stateinstance',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_instances', to='django_telegram.Message'),
        ),
    ]
