# Generated by Django 2.1.2 on 2019-01-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0024_handlerinstance_add_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='update_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
