# Generated by Django 2.1.2 on 2019-01-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0025_update_update_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handler',
            name='filter_path',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
