# Generated by Django 2.1.2 on 2019-01-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0027_message_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='new_chat_members',
            field=models.ManyToManyField(related_name='added_to_chat_messages', to='django_telegram.User'),
        ),
    ]
