# Generated by Django 2.1.2 on 2019-01-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0030_auto_20190124_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramclientapi',
            name='username',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
