# Generated by Django 2.1.2 on 2019-01-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0031_telegramclientapi_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramclientapi',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
