# Generated by Django 2.1.2 on 2019-01-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0034_auto_20190131_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chat_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
