"""Added column to users

Revision ID: 0aae436287df
Revises: e9221fb13c3d
Create Date: 2020-04-26 23:11:35.488687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aae436287df'
down_revision = 'e9221fb13c3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_job', sa.Column('language_code', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_job', 'language_code')
    # ### end Alembic commands ###
