"""Init. Added base tables.

Revision ID: 7c2a3c1790ba
Revises: 
Create Date: 2020-04-27 00:27:12.456028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c2a3c1790ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('small_file_id', sa.String(), nullable=False),
    sa.Column('big_file_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vcard', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chat',
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('PRIVATE', 'GROUP', 'SUPERGROUP', 'CHANNEL', name='chat_types'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('all_members_are_administrators', sa.Boolean(), nullable=False),
    sa.Column('photo', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('invite_link', sa.String(), nullable=True),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('sticker_set_name', sa.String(), nullable=True),
    sa.Column('can_set_sticker_set', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['photo'], ['chat_photo.id'], ),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('message',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('from_user', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('chat', sa.BigInteger(), nullable=False),
    sa.Column('forward_from', sa.Integer(), nullable=True),
    sa.Column('forward_from_chat', sa.BigInteger(), nullable=True),
    sa.Column('forward_from_message_id', sa.Integer(), nullable=True),
    sa.Column('forward_date', sa.DateTime(), nullable=True),
    sa.Column('reply_to_message', sa.Integer(), nullable=True),
    sa.Column('edit_date', sa.DateTime(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('contact', sa.Integer(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat'], ['chat.chat_id'], ),
    sa.ForeignKeyConstraint(['contact'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['forward_from'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['forward_from_chat'], ['chat.chat_id'], ),
    sa.ForeignKeyConstraint(['forward_from_message_id'], ['message.message_id'], ),
    sa.ForeignKeyConstraint(['from_user'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['location'], ['location.id'], ),
    sa.ForeignKeyConstraint(['reply_to_message'], ['message.message_id'], ),
    sa.PrimaryKeyConstraint('message_id'),
    sa.UniqueConstraint('location')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    op.drop_table('chat')
    op.drop_table('user')
    op.drop_table('location')
    op.drop_table('contact')
    op.drop_table('chat_photo')
    # ### end Alembic commands ###
